import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#228c80',
  },
  UserImage: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 10,
    backgroundColor: '#FFFFFF',
    borderColor: '#f79307',
    width: 170,
    height: 170,
    borderRadius: 100,
    marginBottom: 54,
    marginTop: 60,
  },
  Image: {
    width: 150,
    height: 150,
  },
  form: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputEmail: {
    backgroundColor: '#FFF',
    width: 250,
    height: 35,
    borderRadius: 5,
    padding: 5,
  },
  inputPassword: {
    backgroundColor: '#FFF',
    marginTop: 13,
    width: 250,
    height: 35,
    borderRadius: 5,
    padding: 5,
  },
  buttonForm: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 5,
    width: 250,
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  textButton: {
    color: '#228c80',
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'uppercase',
  },
  ButtonCreate: {
    color: '#FFF',
    fontWeight: 'bold',
    marginTop: 20,
    fontSize: 14,
  },
  loadingButton: {
    zIndex: 9999,
    position: 'absolute',
    backgroundColor: '#000',
    height: '100%',
    width: '100%',
    opacity: 0.5,
  },
});
